from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    TIMER_NOT_FOUND = "TIMER_NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
