import uuid
from typing import Protocol

from src.models import Timer


class TimerAsyncInterface(Protocol):
    async def create(self, timer: Timer) -> Timer: ...

    async def get_by_id(self, timer_id: uuid.UUID) -> Timer | None: ...


class TimerSyncInterface(Protocol):
    def get_pending_for_update(self, timer_id: str) -> Timer | None: ...

    def get_overdue_pending(self, limit: int = 500) -> list[Timer]: ...

    def mark_executed(self, timer: Timer) -> None: ...

    def mark_failed(self, timer: Timer) -> None: ...

    def rollback(self) -> None: ...
