"""create_timers_table

Revision ID: 6216c08cd03a
Revises: 
Create Date: 2026-04-01 17:57:30.925764
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6216c08cd03a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('executed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('failed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'executed', 'failed', name='timer_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('dispatched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (status = 'pending'    AND executed_at IS NULL AND failed_at IS NULL)\n            OR\n            (status = 'processing' AND executed_at IS NULL AND failed_at IS NULL)\n            OR\n            (status = 'executed'   AND executed_at IS NOT NULL AND failed_at IS NULL)\n            OR\n            (status = 'failed'     AND executed_at IS NULL AND failed_at IS NOT NULL)\n            ", name='ck_timers_status_timestamp_consistency'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_timers_attempt_count_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timers_overdue_candidates', 'timers', ['scheduled_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'processing')"))
    op.create_index('ix_timers_pending_undispatched', 'timers', ['scheduled_at'], unique=False, postgresql_where=sa.text("status = 'pending' AND dispatched_at IS NULL"))
    op.create_index('ix_timers_status_scheduled_at', 'timers', ['status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timers_status_scheduled_at', table_name='timers')
    op.drop_index('ix_timers_pending_undispatched', table_name='timers', postgresql_where=sa.text("status = 'pending' AND dispatched_at IS NULL"))
    op.drop_index('ix_timers_overdue_candidates', table_name='timers', postgresql_where=sa.text("status IN ('pending', 'processing')"))
    op.drop_table('timers')
    # ### end Alembic commands ###

