"""create_timers_table

Revision ID: 82940397e5e9
Revises: 
Create Date: 2026-03-31 19:12:31.382135
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '82940397e5e9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('executed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'executed', 'failed', name='timer_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (status = 'pending' AND executed_at IS NULL)\n            OR\n            (status = 'processing' AND executed_at IS NULL)\n            OR\n            (status = 'executed' AND executed_at IS NOT NULL)\n            OR\n            (status = 'failed')\n            ", name='ck_timers_status_executed_at_consistency'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timers_status_scheduled_at', 'timers', ['status', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timers_status_scheduled_at', table_name='timers')
    op.drop_table('timers')
    sa.Enum(name='timer_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

