"""add_dispatched_at_column

Revision ID: c2c3ca3b7d42
Revises: e82c6546a14b
Create Date: 2026-04-01 15:13:29.832680
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c2c3ca3b7d42'
down_revision: str | None = 'e82c6546a14b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timers', sa.Column('dispatched_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timers', 'dispatched_at')
    # ### end Alembic commands ###

